### ISSUE TITLE
A question about the activation functions

### ISSUE THREAD

**Issue by iced-cappuccino** [jesbu1/hidio#11]
Hi, could you tell me what the final-layer activation functions the _scheduler_ and the _feature extractor_ used respectively? Thanks!

**Comment by jesbu1** [comment]
The scheduler has a tanh at the end, see: https://github.com/jesbu1/alf/blob/def59fe39bdbca70a6c80e9b8f2c7c785cb59ea7/alf/networks/projection_networks.py#L91 and https://github.com/jesbu1/hidio/blob/master/hidio/examples/hierarchical_goaltask.gin#L51.

This tanh is then scaled to the action dimension ranges of the environment.

Therefore, the feature extractor also has a tanh:
https://github.com/jesbu1/hidio/blob/master/hidio/examples/hierarchical_goaltask.gin#L117

**Comment by iced-cappuccino** [comment]
Thanks very much for your reply!

Could you tell me how the feature extractor is trained in details, such as the loss function and the data format used for training?  Thanks!

**Comment by jesbu1** [comment]
The relevant function for training the feature extractor is here: https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/algorithm/skill_generator.py#L203

The loss function here is essentially simple MSE loss (as we're minimizing the logprob of a Gaussian distribution, see https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/algorithm/skill_generator.py#L242), and the input data depends on the feature extractor instantiation. For example, if we're only looking at the current state, then the input to the feature extractor is the raw state: https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/algorithm/skill_generator.py#L214
