### ISSUE TITLE
Exception in thread Thread-6

### ISSUE THREAD

**Issue by www2171668** [jesbu1/hidio#2]
Hello. When I run the "python -m alf.bin.train --gin_file hierarchical_pusher.gin --root_dir="LOG_DIR"", I meet the problem "Exception in thread Thread-6".  Or, I guess the problem comes from "No such file or directory: b' "? Can you give me some help? Thank you.

The whole problem show as:

`[[A(alf) [www2171668@localhost examples]$ python -m alf.bin.train --gin_file hierarchical_pusher.gin --root_dOG_DIR
I0811 21:15:53.809824 140246770095936 parallel_environment.py:91] Spawning all processes.
I0811 21:15:54.316220 140246770095936 parallel_environment.py:98] All processes started.
I0811 21:15:54.383076 140246770095936 policy_trainer.py:128] observation_spec=BoundedTensorSpec(shape=(20,), dtype=torch.float32, minimum=array(-inf, dtype=float32), maximum=array(inf, dtype=float32))
I0811 21:15:54.383805 140246770095936 policy_trainer.py:129] action_spec=BoundedTensorSpec(shape=(7,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
Skill spec: BoundedTensorSpec(shape=(8,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
I0811 21:15:57.304994 140246770095936 sac_algorithm.py:79] Target entropy is calculated for Higher_level_SAC: -7.330325839756005.
W0811 21:15:57.309831 140246770095936 common.py:712] last_kernel_initializer is not specified for the last layer of size 8.
I0811 21:15:57.651582 140246770095936 sac_algorithm.py:79] Target entropy is calculated for Lower_level_SAC: -6.414035109786505.
I0811 21:15:57.729449 140246770095936 checkpoint_utils.py:83] Checkpoint 'latest' is loaded successfully.
/home/www2171668/HIDIO/alf/alf/utils/summary_utils.py:92: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729006826/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  bucket_min = torch.as_tensor(bucket_min)
/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/torch/cuda/memory.py:234: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  FutureWarning)
I0811 21:15:59.671370 140246770095936 policy_trainer.py:234] ['hierarchical_pusher.gin'] -> ['LOG_DIR']: 2 time=1.933 throughput=0.00
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 211, in run
    self._record_writer.write(data)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/summary/writer/record_writer.py", line 39, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 507, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 150, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 154, in _write
    with io.open(filename, mode, encoding=encoding) as f:
**FileNotFoundError: [Errno 2] No such file or directory: b'LOG_DIR/train/events.out.tfevents.1628687757.localhost.localdomain.20761.1'**`

**Comment by www2171668** [comment]
[[A(alf) [www2171668@localhost examples]$ python -m alf.bin.train --gin_file hierarchical_pusher.gin --root_dOG_DIR
I0811 21:15:53.809824 140246770095936 parallel_environment.py:91] Spawning all processes.
I0811 21:15:54.316220 140246770095936 parallel_environment.py:98] All processes started.
I0811 21:15:54.383076 140246770095936 policy_trainer.py:128] observation_spec=BoundedTensorSpec(shape=(20,), dtype=torch.float32, minimum=array(-inf, dtype=float32), maximum=array(inf, dtype=float32))
I0811 21:15:54.383805 140246770095936 policy_trainer.py:129] action_spec=BoundedTensorSpec(shape=(7,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
Skill spec: BoundedTensorSpec(shape=(8,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
I0811 21:15:57.304994 140246770095936 sac_algorithm.py:79] Target entropy is calculated for Higher_level_SAC: -7.330325839756005.
W0811 21:15:57.309831 140246770095936 common.py:712] last_kernel_initializer is not specified for the last layer of size 8.
I0811 21:15:57.651582 140246770095936 sac_algorithm.py:79] Target entropy is calculated for Lower_level_SAC: -6.414035109786505.
I0811 21:15:57.729449 140246770095936 checkpoint_utils.py:83] Checkpoint 'latest' is loaded successfully.
/home/www2171668/HIDIO/alf/alf/utils/summary_utils.py:92: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729006826/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  bucket_min = torch.as_tensor(bucket_min)
/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/torch/cuda/memory.py:234: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  FutureWarning)
I0811 21:15:59.671370 140246770095936 policy_trainer.py:234] ['hierarchical_pusher.gin'] -> ['LOG_DIR']: 2 time=1.933 throughput=0.00
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 211, in run
    self._record_writer.write(data)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/summary/writer/record_writer.py", line 39, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 507, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 150, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/www2171668/.conda/envs/alf/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 154, in _write
    with io.open(filename, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: b'LOG_DIR/train/events.out.tfevents.1628687757.localhost.localdomain.20761.1'

**Comment by hnyu** [comment]
Hi, this error comes from your Tensorboard. Which version do you have? From our experience, Tensorboard 2.x should have no problem.

**Comment by www2171668** [comment]
My Tensorboard is 2.1.0. I check other gin. ac_breakout has no this problem. But ddpg, diayn and hidio have this problem.
![image](https://user-images.githubusercontent.com/49861957/129348772-e4058c15-6897-47b9-a0eb-7e3bc5bfe83d.png)

**Comment by www2171668** [comment]
![image](https://user-images.githubusercontent.com/49861957/129348849-be71637c-1e8a-4fcf-bca8-9f6370042a5b.png)

**Comment by www2171668** [comment]
I got it. In this env, I forget to install tensorflow. I deal with it with tensorflow 2.1.0.  Thank you very much.
