### ISSUE TITLE
Can hidio be used in discrete action spaces?

### ISSUE THREAD

**Issue by wangjw55** [jesbu1/hidio#3]
Hello, I recently wanted to use hidio in an environment with discrete action space like gym_cart_pole, but the shape of the action is ( ), and the function 'get_low_rl_input_spec' in the hierarchical_agent.py file needs to get the shape[0] of the action_spec, then an error will occur. Can you help me to deal with this problem? Thank you.

**Comment by jesbu1** [comment]
Hi, I will take a look either in the next few days or this weekend and get back to you!

**Comment by jesbu1** [comment]
HIDIO does not specifically support discrete action spaces in the current build, sorry! It can, but there are quite a few modifications to be made to support it. If you wanted to use an environment like cartpole, then you can use the Mujoco cartpole (or if you don't have a Mujoco license, the Pybullet cartpole https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/bullet/cartpole_bullet.py)
