### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by sunsibar** [jesbu1/hidio#5]
Hi again,

How long does it usually take to train hidio, for example on pusher or reacher?

I'm running it now with default parameters, and it does not seem to be using the GPU to full capacity.
It is also rather slow; comparing it with the plots (fig. 4) in your paper, convergence seems to start at around 500'000 epochs. At the current speed (3-5s/epoch), getting to 500k epochs would take around 28 days. Also, the time per epoch seems to _slow down_ a lot (to 150s/epoch after a day).

Is this expected? 

Apologies if I overlooked this training information in your paper, I wasn't able to find it there.

**Comment by hnyu** [comment]
Hi @sunsibar , as I recall a single run won't take so many days. Our machine was Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz with 32 CPUs and a memory of 64G, and the GPU is 2080ti. @jesbu1 can provide you with more accurate running time.

One thing to note is that Fig. 4 shows number of env steps as the x axis; it's not the "epoch" or "iteration". One epoch or iteration could consist of many env steps, especially multiple parallel envs are used to collect experiences. So It seems normal to me that one epoch takes several seconds (if by "epoch" you mean one iteration in ALF's terminology). 

The best way to find out how many env steps the training has processed so far would be to open the tensorboard of your training job and under the "Metrics_vs_EnvironmentSteps" tab you will see all plots have num of env steps as the x axes.

**Comment by jesbu1** [comment]
Hi @sunsibar and thanks @hnyu for the detailed response. 

In terms of running time, we on our machine it took around ~5 hours. I have the actual runs on a separate hard drive I will have access to in a few days, I can check the exact running time then and report back.

**Comment by sunsibar** [comment]
Thank you both very much, and no need to check the running time more precisely than that. That answers my question completely. I'll double check why I had the impression that it hadn't converged within a day, maybe I misread and it actually did converge.

**Comment by sunsibar** [comment]
Nonsense, it totally did converge! Thanks :D
