### ISSUE TITLE
Training with Discriminator.skill_type="action_concatenation"

### ISSUE THREAD

**Issue by sunsibar** [jesbu1/hidio#6]
It's me again, I was wondering how one would run the alternative skill-types in your paper. Just replacing the skill_type Parameter in the .gin file (here for hierarchical_pusher.gin) results in an error: 

```
[...]
  File "|||||||||||||||||||||||||||||||||<hidio_py37/alf/alf/networks/preprocessor_networks.py", line 109, in __init__
    input_tensor_spec = preprocessing_combiner(input_tensor_spec)
  File "|||||||||||||||||||||||||||||||||hidio_py37/alf/alf/nest/utils.py", line 62, in __call__
    lambda spec: spec.zeros(outer_dims=(1, )), flat)
  File "|||||||||||||||||||||||||||||||||hidio_py37/alf/alf/nest/nest.py", line 52, in map_structure
    raise e
  File "|||||||||||||||||||||||||||||||||hidio_py37/alf/alf/nest/nest.py", line 47, in map_structure
    return cnest.map_structure(func, *nests)
  File "|||||||||||||||||||||||||||||||||hidio_py37/alf/alf/nest/utils.py", line 62, in <lambda>
    lambda spec: spec.zeros(outer_dims=(1, )), flat)
AttributeError: 'numpy.int64' object has no attribute 'zeros'
  In call to configurable 'EncodingNetwork' (<class 'alf.networks.encoding_networks.EncodingNetwork'>) in scope 'disc'
  In call to configurable 'Discriminator' (<class 'hidio.algorithm.skill_generator.Discriminator'>)
  In call to configurable 'SkillGenerator' (<class 'hidio.algorithm.skill_generator.SkillGenerator'>)
  In call to configurable 'HierarchicalAgent' (<class 'hidio.algorithm.hierarchical_agent.HierarchicalAgent'>)
  In call to configurable 'train_eval' (<function train_eval at 0x2aac1d9743b0>)
Skill spec: BoundedTensorSpec(shape=(8,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
``` 

And I have another question that I'll post in a bit - this question here is more out of curiosity. So far we don't need it. (So the other one is more important.)

**Comment by hnyu** [comment]
It's supposed to work by directly replacing the skill_type. @jesbu1 Can you take a look at this issue? Thanks

**Comment by sunsibar** [comment]
It might be because it only tests the first element in flat for its type, and it seems flat can have mixed types 
(in nest/utils.py)
Aha, this is also alf, so maybe it is fixed since long in a newer version.

**Comment by jesbu1** [comment]
Can you please revert your change in `skill_generator.py` and then pull again? The issue should be fixed, the original functions being called for concatenation skill types were named incorrectly to begin with, and also there were two alf TensorSpec functions that were missing that are needed to get these skill types to work. 

I added those as functions to `hidio/hidio/utils.py` and then tested. Seems to be working for both concatenation types on my end now.
